### ISSUE TITLE
checkResult.py -IOError: 

### ISSUE THREAD

**Issue by tha-uzhavan** [noolahamfoundation/ocr-tooling#1]
The following error coming while executing checkResult.py
`root@ember2:/var/www/html/ocr/ocr-by-batch-number/OCT-2016-ocr-6# python checkResult.py 
Traceback (most recent call last):
  File "checkResult.py", line 13, in <module>
    batchFile = open(folderPath + "/" + batchFileName)
IOError: [Errno 2] No such file or directory: '/var/www/html/ocr/ocr-by-batch-number/OCT-2016-ocr-s/batchdata.csv'
`

**Comment by tha-uzhavan** [comment]
even though, i gave right path,  the output (checkResults_batchdata.txt) file is not coming.

**Comment by Natkeeran** [comment]
issue வைப் பதிவு செய்தற்கு நன்றி.  நீங்கள் கொடுத்த folderpath இல் தவறு உள்ளதாகக் கருதுகிறேன்.  folderPath பின்வருமாறு அமைய வேண்டும்

folderPath = "/var/www/html/ocr/ocr-by-batch-number/OCT-2016-ocr-6/" 

நீங்கள் கொடுத்த வழி /var/www/html/ocr/ocr-by-batch-number/OCT-2016-ocr-s/ உள்ளது போல் இருக்கின்றது.  அது மேலே குறிப்பிட்டுள்ளது போன்று குடுக்கும் போது நிரல் வேலை செய்கிறது.

**Comment by tha-uzhavan** [comment]
ஆம். கோப்பு அமைனவிடத்தை மாற்றி செய்த போதும், அந்த வழு இருப்பதாகத்தவறாக எண்ணினேன். எழுத்துணரியாக்கம் முடிந்த பிறகு,தேவையற்ற கோப்புகளை நீக்கி கண்டபோது, எழுத்துணரியாக்க விளைவு நிரலின்(checkResult.py) சரியான செயற்பாட்டினை கண்டேன்.  இனி கவனமாக செயற்படுகிறேன். உங்கள் ஒத்துழைப்புக்கு நன்றி. வணக்கம்
