### ISSUE TITLE
@ batchocr.py - IndexError: list index out of range

### ISSUE THREAD

**Issue by tha-uzhavan** [noolahamfoundation/ocr-tooling#2]
path: root@ember2:/var/www/html/ocr/ocr-by-batch-number/OCT-2016-ocr-8
என்பதில் python batchocr.py இயக்கினால், கீழ்கண்ட வழு வருகிறது.

`Traceback (most recent call last):
  File "batchocr.py", line 43, in <module>
    columnNum = row[9]
IndexError: list index out of range
`அனைத்து கோப்புகளையும் அங்குள்ளன.
https://docs.google.com/spreadsheets/d/15Fi5LA-yIZ0IQYueC1fa7MhwUza5SRgneaXHRe-gzk0/edit?usp=sharing (to verify batchdata.csv)

**Comment by Natkeeran** [comment]
batchocr.py இன் புதிய பதிப்புடன் பரிசோதிக்கவும்.  நன்றி.

**Comment by tha-uzhavan** [comment]
வழு களைந்தமைக்கு நன்றி.மேற்கூறிய கோப்பு அமைவிடத்தில், தற்போது இயங்குகிறது.
